### ISSUE TITLE
Build error - PocketSVG

### ISSUE THREAD

**Issue by alelordelo** [t-StudioAB/2D-3D-Pattern-editing-Demo-#1]
Installed Pod, but got error with PocketSVG

<img width="1440" alt="screen shot 2018-12-10 at 21 08 25" src="https://user-images.githubusercontent.com/17708751/49758647-d9554f80-fcbf-11e8-9d62-f64510fee081.png">
alexandres-mbp:~ alexandrelordelo$ cd /Users/alexandrelordelo/Downloads/2D-3D-Pattern-editing-Demo--master-4/ModelEditor/ModelEditor.xcodeproj 
alexandres-mbp:ModelEditor.xcodeproj alexandrelordelo$ pod install
[in /Users/alexandrelordelo/Downloads/2D-3D-Pattern-editing-Demo--master-4/ModelEditor]
Analyzing dependencies
Downloading dependencies
Installing PocketSVG (2.4.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

[!] [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

[!] [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

[!] Automatically assigning platform `ios` with version `12.1` on target `ModelEditor` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
alexandres-mbp:ModelEditor.xcodeproj alexandrelordelo$ pod install
[in /Users/alexandrelordelo/Downloads/2D-3D-Pattern-editing-Demo--master-4/ModelEditor]
Analyzing dependencies
Downloading dependencies
Using PocketSVG (2.4.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

[!] [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

[!] [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

[!] Automatically assigning platform `ios` with version `12.1` on target `ModelEditor` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by justaninja** [comment]
@alelordelo Did you open the project with ModelEditor.xcworkspace file (white icon)?
